try using GH reusable workflow
Xabaril/AspNetCore.Diagnostics.HealthChecks pull request #2037
Opened 2023-09-14 10:52 UTC by adamsitnik

2023-09-14 11:38 UTC, adamsitnik commented
@lfraile it's ready for review, PTAL

2023-09-14 15:10 UTC, lfraile requested changes

2023-09-14 15:10 UTC, lfraile commented on .github/workflows/healthchecks_azurekeyvault_cd_preview.yml
> +    uses: ./.github/workflows/reusable_cd_preview_workflow.yml
```suggestion
    uses: ./.github/workflows/reusable_cd_preview_workflow.yml
    secrets: inherit
```
We will need this so we can use ${{secrets.NUGET_API_KEY}}

2023-09-14 15:10 UTC, lfraile commented on .github/workflows/healthchecks_azurekeyvault_cd.yml
> +    uses: ./.github/workflows/reusable_cd_workflow.yml
```suggestion
    uses: ./.github/workflows/reusable_cd_workflow.yml
    secrets: inherit
```
We will need this so we can use ${{secrets.NUGET_API_KEY}}

2023-09-15 12:31 UTC, adamsitnik commented
@lfraile great catch! I've applied your suggestion to all files, PTAL

2023-09-15 12:33 UTC, lfraile approved these changes

2023-09-15 12:39 UTC, merged

2023-12-03 17:05 UTC, sungam3r commented
@adamsitnik Thank you very much for that!