Added managed identity for Azure IoTHub health checks
Xabaril/AspNetCore.Diagnostics.HealthChecks pull request #2216
Opened 2024-05-16 12:46 UTC by brattpurrie

**What this PR does / why we need it**:
Implements managed identity for Azure IoT hubs and resolves socket starvation / memory leak.

**Which issue(s) this PR fixes**:
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/2211

Please reference the issue this PR will close: #_[issue number]_
#2211

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

Please make sure you've completed the relevant tasks for this PR, out of the following list:

- [x] Code compiles correctly
- [x] Created/updated tests
- [x] Unit tests passing
- [x] End-to-end tests passing
- [x] Extended the documentation
- [x] Provided sample for the feature

2024-05-16 12:52 UTC, brattpurrie commented
@dotnet-policy-service agree company="Microsoft"

2024-05-16 12:59 UTC, pregress approved these changes

2024-09-16 09:00 UTC, brattpurrie commented
@sungam3r Do you have the permissions to merge this?

2024-12-13 09:19 UTC, adamsitnik requested changes
Thank yo for your contribution @brattpurrie ! Overall it looks good, but we need to remove the empty options class.

2024-12-13 09:19 UTC, adamsitnik commented on src/HealthChecks.Azure.IoTHub/DependencyInjection/IoTHubHealthChecksBuilderExtensions.cs
> +        string? name = default,
nit: we can provide the default name since we know it

```suggestion
        string? name = NAME_SERVICE_CLIENT,
```

2024-12-13 09:19 UTC, adamsitnik commented on src/HealthChecks.Azure.IoTHub/DependencyInjection/IoTHubHealthChecksBuilderExtensions.cs
> +    /// /// An optional factory to obtain <see cref="RegistryManager" /> instance.
```suggestion
    /// An optional factory to obtain <see cref="RegistryManager" /> instance.
```

2024-12-13 09:19 UTC, adamsitnik commented on src/HealthChecks.Azure.IoTHub/DependencyInjection/IoTHubHealthChecksBuilderExtensions.cs
> +    /// /// An optional factory to obtain <see cref="ServiceClient" /> instance.
```suggestion
    /// An optional factory to obtain <see cref="ServiceClient" /> instance.
```

2024-12-13 09:19 UTC, adamsitnik commented on src/HealthChecks.Azure.IoTHub/IoTHubServiceClientHealthCheck.cs
> +        _options = options ?? new IotHubServiceClientOptions();
those options are not used anywhere, we should just remove them?

2024-12-13 09:19 UTC, adamsitnik commented on src/HealthChecks.Azure.IoTHub/IotHubServiceClientOptions.cs
> +public sealed class IotHubServiceClientOptions;
this type should just be removed

2024-12-13 09:19 UTC, adamsitnik commented on test/HealthChecks.Azure.IoTHub.Tests/HealthChecks.Azure.IoTHub.Tests.csproj
> +    <PackageReference Include="Azure.Identity" Version="1.10.5" />
in the meantime we have merged CPM, so providing a version is not needed here

```suggestion
    <PackageReference Include="Azure.Identity" />
```

2024-12-13 10:56 UTC, adamsitnik approved these changes
@brattpurrie since this PR was stale due to lack of any response from ours (maintainers) side and I want to release 9.0 today I decided to take some time and address my comments and push to your fork. I hope you don't mind.

Again, thank you for your contribution!

2024-12-13 10:59 UTC, merged