Allow passing AWS credentials directly to Amazon S3 and DynamoDB healthcheck
Xabaril/AspNetCore.Diagnostics.HealthChecks pull request #817
Opened 2021-08-08 16:04 UTC by jakubriha

**What this PR does / why we need it**:
It allows to directly pass `AWSCredentials` object instance to Amazon S3 and DynamoDB healthchecks. This extends use-cases for providing such credentials, like credentials loaded from application's default configuration. This PR was built upon the work of @jocco in his PR #653.

**Which issue(s) this PR fixes**:
close #482

**Special notes for your reviewer**:
No

**Does this PR introduce a user-facing change?**:
The PR makes `AccessKey` and `SecretKey` properties in `S3BucketOptions` and `DynamoDbOptions` obsolete. Instead, it provides new property `Credentials`, which provides the same functionality. However, the obsolete properties are still functioning if the `Credentials` property is not passed.

2021-10-29 20:07 UTC, sungam3r commented on src/HealthChecks.Aws.S3/S3BucketOptions.cs
> +        public AWSCredentials Credentials {get; set;}
```suggestion
        public AWSCredentials Credentials { get; set; }
```

2021-10-29 20:07 UTC, sungam3r commented on src/HealthChecks.Aws.S3/README.md
> +            options.S3Config = new AmazonS3Config()
```suggestion
            options.S3Config = new AmazonS3Config
```

2021-10-29 20:09 UTC, sungam3r commented on src/HealthChecks.Aws.S3/S3BucketOptions.cs
> +        [Obsolete("Specify access key and secret as a BasicCredential to AWSCredentials instead")]
```suggestion
        [Obsolete("Specify access key and secret as a BasicAWSCredentials to Credentials property instead")]
```

2021-10-29 20:09 UTC, sungam3r commented on src/HealthChecks.Aws.S3/S3BucketOptions.cs
> +        [Obsolete("Specify access key and secret as a BasicCredential to AWSCredentials instead")]
```suggestion
        [Obsolete("Specify access key and secret as a BasicAWSCredentials to Credentials property instead")]
```

2021-10-29 20:12 UTC, sungam3r commented on src/HealthChecks.DynamoDb/DynamoDbOptions.cs
> +        [Obsolete("Specify the access key and secret as a BasicCredential to the Credentials Field instead")]
```suggestion
        [Obsolete("Specify the access key and secret as a BasicAWSCredentials to the Credentials property instead")]

```

2021-10-29 20:12 UTC, sungam3r commented on src/HealthChecks.DynamoDb/DynamoDbOptions.cs
> +        [Obsolete("Specify the access key and secret as a BasicCredential to the Credentials Field instead")]
```suggestion
        [Obsolete("Specify the access key and secret as a BasicAWSCredentials to the Credentials property instead")]

```

2021-10-30 07:31 UTC, jakubriha commented
@sungam3r Thank you for code review suggestions. All of them have been applied.

2022-02-24 00:02 UTC, sungam3r commented
@jakubriha Please rebase onto `master`. CI has been changed drastically.

2022-05-30 05:26 UTC, sungam3r commented
ping @jakubriha

2022-06-25 17:46 UTC, jakubriha commented
@sungam3r Rebase has been done.

2022-06-25 20:40 UTC, sungam3r requested changes

2022-06-25 20:40 UTC, sungam3r commented on src/HealthChecks.Aws.S3/README.md
> +```cs
```suggestion
```csharp
```

2022-06-25 20:40 UTC, sungam3r commented on src/HealthChecks.Aws.S3/README.md
> +```cs
```suggestion
```csharp
```

2022-06-25 20:40 UTC, sungam3r commented on src/HealthChecks.DynamoDb/README.md
> +- `name`: The health check name. Default if not specified is `aws s3`.
```suggestion
- `name`: The health check name. Default if not specified is `dynamodb`.
```

2022-06-25 20:40 UTC, sungam3r commented on src/HealthChecks.DynamoDb/README.md
> +```cs
```suggestion
```csharp
```

2022-06-25 20:40 UTC, sungam3r commented on src/HealthChecks.DynamoDb/README.md
> +```cs
```suggestion
```csharp
```

2022-06-25 20:40 UTC, sungam3r commented on test/UnitTests/DependencyInjection/S3/S3UnitTests.cs
> +            var options = serviceProvider.GetService<IOptions<HealthCheckServiceOptions>>();
```suggestion
            var options = serviceProvider.GetRequiredService<IOptions<HealthCheckServiceOptions>>();
```

2022-06-25 20:40 UTC, sungam3r commented on test/UnitTests/DependencyInjection/S3/S3UnitTests.cs
> +        [Fact]
```suggestion

        [Fact]
```

2022-06-25 20:40 UTC, sungam3r commented on test/UnitTests/DependencyInjection/S3/S3UnitTests.cs
> +            var options = serviceProvider.GetService<IOptions<HealthCheckServiceOptions>>();
```suggestion
            var options = serviceProvider.GetRequiredService<IOptions<HealthCheckServiceOptions>>();
```

2022-06-25 20:40 UTC, sungam3r commented on test/UnitTests/DependencyInjection/S3/S3UnitTests.cs
> +            var serviceProvider = services.BuildServiceProvider();
```suggestion
            using var serviceProvider = services.BuildServiceProvider();
```

2022-06-25 20:40 UTC, sungam3r commented on test/UnitTests/DependencyInjection/S3/S3UnitTests.cs
> +            var serviceProvider = services.BuildServiceProvider();
```suggestion
            using var serviceProvider = services.BuildServiceProvider();
```

2022-06-25 20:40 UTC, sungam3r commented on src/HealthChecks.UI/package-lock.json
>  {
Please revrert all changes in this file.

2022-06-26 07:30 UTC, sungam3r commented
I suppose #653 could be closed after merging this one?

2022-06-26 07:31 UTC, sungam3r commented
I'm fine to merge afer fixin formatting issues.

2022-06-26 08:29 UTC, jakubriha commented
> I suppose #653 could be closed after merging this one?

Yes, it can be closed.

2022-06-26 08:51 UTC, sungam3r commented
A bit more work here.

2022-06-26 20:37 UTC, sungam3r commented
You still have to update api approval file since `Obsolete` attribute affects public API surface.

2022-06-27 03:55 UTC, jakubriha commented
> You still have to update api approval file since `Obsolete` attribute affects public API surface.

Hopefully, the last commit should fix this.

2022-06-27 10:27 UTC, sungam3r approved these changes

2022-06-27 10:29 UTC, merged